name: ssh-krb-node-executor
rundeckPluginVersion: 1.0
author: Akos Hencz, Daniel Fernández, Philippe Ganz
date: 2018-08-29
url: https://github.com/cernops/rundeck-exec-kerberos
version: 1.5.0
providers:
    - name: ssh-krb
      service: NodeExecutor
      title: SSH Kerberos Executor
      description: Execute a command on a remote node using SSH, authenticating using a Kerberos ticket
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: ssh-krb-executor.sh
      script-args: ${node.username} ${node.hostname} ${exec.command}
      config:
        - name: kerberos_user
          title: Kerberos user
          type: String
          required: true
          description: "The user who gets Kerberos tickets using the keytab"
        - name: kerberos_keytab
          title: Kerberos keytab
          type: String
          required: true
          description: "The path and filename to the Kerberos key table used to authenticate the user (e.g. /tmp/user.ktab)"
        - name: use_kerberos_custom_cache_file
          title: Use a dedicated cache file
          type: Boolean
          required: false
          description: "If selected, the Kerberos credentials cache file will be stored in a dedicated location. Recommended when multiple Kerberos principals are in use in this Rundeck instance because initiating another principal will override the current principal present in the default cache file, if any."
        - name: kerberos_custom_cache_filename
          title: Kerberos cache filename
          type: String
          required: false
          description: "Define a custom location for the dedicated Kerberos credentials cache file, otherwise it will use the pattern /tmp/krb5cc_<UID>_rundeck_<KERBEROS_USER>"
        - name: do_kdestroy
          title: Destroy kerberos ticket
          type: Boolean
          required: false
          description: "If selected, the kerberos ticket will be destroyed at the end of the execution"

    - name: scp-krb
      service: FileCopier
      title: SCP Kerberos Executor
      description: Copies the file to a remote node using SCP, authenticating using a Kerberos ticket
      plugin-type: script
      script-interpreter: /bin/bash
      script-file: scp-krb-executor.sh
      script-args: ${node.username} ${node.hostname} ${file-copy.file} ${file-copy.destination}
      config:
        - name: kerberos_user
          title: Kerberos user
          type: String
          required: true
          description: "The user who gets Kerberos tickets using the keytab"
        - name: kerberos_keytab
          title: Kerberos keytab
          type: String
          required: true
          description: "The path and filename to the Kerberos key table used to authenticate the user (e.g. /tmp/user.ktab)"
        - name: use_kerberos_custom_cache_file
          title: Use a dedicated cache file
          type: Boolean
          required: false
          description: "If selected, the Kerberos credentials cache file will be stored in a dedicated location. Recommended when multiple Kerberos principals are in use in this Rundeck instance because initiating another principal will override the current principal present in the default cache file, if any."
        - name: kerberos_custom_cache_filename
          title: Kerberos cache filename
          type: String
          required: false
          description: "Define a custom location for the dedicated Kerberos credentials cache file, otherwise it will use the pattern /tmp/krb5cc_<UID>_rundeck_<KERBEROS_USER>"
        - name: do_kdestroy
          title: Destroy kerberos ticket
          type: Boolean
          required: false
          description: "If selected, the kerberos ticket will be destroyed at the end of the execution"
